#My First Workflow

name: workflow1
on: 
  workflow_dispatch:
  push:

jobs:
  job1:
    runs-on: self-hosted
    steps: 
      - name: step1
        run: |
          echo "Good Morning People"
          sleep 30
      - name: step2 for testing
        run: |
          cat /etc/os-release
          hostname
          touch /tmp/sue169
          sleep 30
## Name is not important in a step
      - run: uname -a
